"""
api/parse-mfc.py
FastAPI endpoint for MF Central Detailed CAS PDF parsing.
Handles MFCentralDetailCAS_v1.2 format (generated by mfcentral.com).
No password needed — user downloads directly from MF Central portal.

POST /api/parse-mfc
  Content-Type: multipart/form-data
  Field: file (PDF)
  Returns: { pan, name, period, holdings[] }
"""

from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pdfminer.high_level import extract_text
from io import BytesIO
import re, urllib.request, json

app = FastAPI()
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["POST", "OPTIONS"],
    allow_headers=["*"],
)

# ── AMFI ISIN → scheme code + live NAV ──────────────────────────────────────
_isin_cache = {}
_cache_time  = 0

def load_amfi_isin_map():
    """Fetch AMFI NAVAll.txt and build ISIN → (scheme_code, scheme_name, nav) map."""
    import time
    global _isin_cache, _cache_time
    now = time.time()
    if _isin_cache and (now - _cache_time) < 3600:    # 1-hour local cache
        return _isin_cache

    req = urllib.request.Request(
        "https://www.amfiindia.com/spages/NAVAll.txt",
        headers={"User-Agent": "MFCalc/2.0"}
    )
    data = urllib.request.urlopen(req, timeout=12).read().decode("utf-8", errors="ignore")
    imap = {}
    for line in data.split("\n"):
        parts = line.strip().split(";")
        if len(parts) < 5:
            continue
        code, isin_g, isin_d, name, nav = parts[0], parts[1], parts[2], parts[3], parts[4]
        if "INF" in isin_g:
            imap[isin_g.strip()] = {"code": code.strip(), "name": name.strip(), "nav": nav.strip()}
        if "INF" in isin_d:
            imap[isin_d.strip()] = {"code": code.strip(), "name": name.strip(), "nav": nav.strip()}
    _isin_cache = imap
    _cache_time  = now
    return imap


# ── Core parser (accepts pre-extracted text) ─────────────────────────────────
def _parse_mfc_text(text: str) -> dict:
    """Parse holdings from already-extracted MF Central CAS text."""

    # ── PAN ──────────────────────────────────────────────────────────────────
    pan_m = re.search(r"PAN\s*:\s*([A-Z]{5}\d{4}[A-Z])", text)
    pan   = pan_m.group(1) if pan_m else ""

    # ── Investor name ─────────────────────────────────────────────────────────
    # MF Central format: investor name is on the line immediately after PAN.
    # Only search within ~200 chars after PAN to avoid picking up scheme names
    # or header text ("Consolidated Account Statement") further in the document.
    name = ""
    if pan_m:
        nearby = text[pan_m.end():pan_m.end() + 200]
        for line in nearby.split("\n"):
            line = line.strip()
            # Names are letters/spaces/dots, 3–50 chars — excludes address lines
            # (B-6. INDRAPURI has digits/hyphens) and long headers (> 50 chars)
            if line and re.match(r"^[A-Za-z][A-Za-z\s\.]{2,49}$", line):
                name = line
                break

    # ── Statement period ──────────────────────────────────────────────────────
    date_m = re.search(
        r"From\s+Date\s*:\s*([\d\-\/A-Za-z]+).*?To\s+Date\s*:\s*([\d\-\/A-Za-z]+)",
        text, re.DOTALL
    )
    period = {
        "from": date_m.group(1).strip() if date_m else "",
        "to":   date_m.group(2).strip() if date_m else "",
    }

    # ── Holdings — split on "FOLIO NO:" (case-insensitive, no newline required) ──
    holdings = []
    folio_blocks = re.split(r"(?i)\bFOLIO\s+NO\s*:\s*", text)[1:]

    for block in folio_blocks:
        # Folio number — first non-whitespace token
        folio_m = re.match(r"(\S+)", block)
        if not folio_m:
            continue
        folio = folio_m.group(1)

        # ISIN — exactly 12 chars starting with INF
        isin_m = re.search(r"\b(INF[A-Z0-9]{9})\b", block)
        if not isin_m:
            continue
        isin = isin_m.group(1)

        # Scheme name — text on the same line before "ISIN:"
        scheme_line_m = re.search(r"([^\n]+?)\s+ISIN\s*:\s*" + re.escape(isin), block)
        if not scheme_line_m:
            # Try: scheme name on one line, ISIN on the next
            scheme_line_m = re.search(
                r"([^\n]{5,120})\n[^\n]*ISIN\s*:\s*" + re.escape(isin), block
            )
        if not scheme_line_m:
            continue
        scheme_name = re.sub(r"\s*\(Advisor:.*?\)\s*", "", scheme_line_m.group(1))
        scheme_name = re.sub(r"\s+", " ", scheme_name).strip()

        # Closing balance — date may use -, /, or . separators
        closing_m = re.search(
            r"Closing Unit Balance\s*:\s*([\d,\.]+)"
            r"\s+Nav as on\s+([\d\w\-\/\.]+)\s*:\s*INR\s*([\d,\.]+)",
            block,
        )
        if not closing_m:
            continue
        units     = float(closing_m.group(1).replace(",", ""))
        nav_date  = closing_m.group(2)
        nav_price = float(closing_m.group(3).replace(",", ""))

        if units == 0:
            continue

        holdings.append({
            "folio":        folio,
            "scheme_name":  scheme_name,
            "isin":         isin,
            "units":        units,
            "nav_pdf":      nav_price,
            "nav_date_pdf": nav_date,
            "value_pdf":    round(units * nav_price, 2),
        })

    return {"pan": pan, "name": name, "period": period, "holdings": holdings}


# ── Endpoint ─────────────────────────────────────────────────────────────────
@app.post("/api/parse-mfc")
async def parse_mfc(file: UploadFile = File(...)):
    if not file.filename.lower().endswith(".pdf"):
        raise HTTPException(400, "Only PDF files are accepted")

    pdf_bytes = await file.read()
    if len(pdf_bytes) > 20 * 1024 * 1024:
        raise HTTPException(400, "File too large (max 20MB)")

    # Extract text once — used for both validation and parsing
    try:
        text = extract_text(BytesIO(pdf_bytes))
    except Exception as e:
        raise HTTPException(400, f"Could not read PDF: {str(e)}")

    # Validate against real full text (not a truncated byte slice)
    if "MFCentralDetailCAS" not in text and "Consolidated Account Statement" not in text:
        raise HTTPException(
            400,
            "This doesn't appear to be an MF Central Consolidated Account Statement. "
            "Please download a Detailed CAS from app.mfcentral.com."
        )

    # Parse holdings from already-extracted text
    try:
        result = _parse_mfc_text(text)
    except Exception as e:
        raise HTTPException(500, f"Parsing error: {str(e)}")

    if not result["holdings"]:
        raise HTTPException(
            422,
            "No holdings found in this statement. "
            "Ensure you are uploading a Detailed (not Summary) statement with non-zero balances."
        )

    # Enrich with live AMFI NAVs via ISIN mapping
    try:
        isin_map = load_amfi_isin_map()
        for h in result["holdings"]:
            amfi = isin_map.get(h["isin"])
            if amfi:
                h["scheme_code"] = amfi["code"]
                h["amfi_name"]   = amfi["name"]
                try:
                    h["nav_live"]   = float(amfi["nav"])
                    h["value_live"] = round(h["units"] * h["nav_live"], 2)
                except ValueError:
                    h["nav_live"]   = h["nav_pdf"]
                    h["value_live"] = h["value_pdf"]
            else:
                h["scheme_code"] = ""
                h["amfi_name"]   = h["scheme_name"]
                h["nav_live"]    = h["nav_pdf"]
                h["value_live"]  = h["value_pdf"]
    except Exception:
        # Live NAV enrichment failed — fall back to PDF NAVs
        for h in result["holdings"]:
            h.setdefault("scheme_code", "")
            h.setdefault("nav_live",    h["nav_pdf"])
            h.setdefault("value_live",  h["value_pdf"])

    return result


@app.get("/api/parse-mfc/health")
async def health():
    return {"status": "ok", "service": "mfc-parser"}


# Vercel Python runtime requires this export for ASGI apps
handler = app
